---
# This playbook deploys a simple standalone Tomcat 7 server.

- name: a simple standalone Tomcat 7 server installation
  connection: local
  gather_facts: false
  vars_files:
    - "group_vars/tomcat-servers.yml"
    - "group_vars/server-inventory.yml"
  hosts: 10.65.217.85
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - selinux
    - tomcat
