---
# This playbook deploys a simple standalone Tomcat 7 server.
 
- name: a simple standalone Tomcat 7 server installation
  connection: local
  gather_facts: false
  vars_files:
    - "group_vars/tomcat-servers.yml"
    - "group_vars/server-inventory.yml"
  hosts: "{{ server }}"
  tasks:
    - debug: var=ansible_facts
    - debug:
        msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
    - debug:
        msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"
  remote_user: sysadmin
  become: yes
  become_method: sudo
  become_user: root
