---
# This playbook deploys a simple standalone Tomcat 7 server.

- name: a simple standalone Tomcat 7 server installation
  connection: local
  gather_facts: true
  vars_files:
    - "group_vars/tomcat-servers.yml"
    - "group_vars/server-inventory.yml"
  hosts: "{{ server }}"
  remote_user: sysadmin
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - selinux
    - tomcat
